services:
  netdata:
    image: netdata/netdata:stable
    hostname: ${NETDATA_HOSTNAME}
    pid: host
    userns_mode: host
    cap_add:
      - SYS_PTRACE
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    volumes:
      - netdataconfig:/etc/netdata
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /etc/localtime:/host/etc/localtime:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - TZ=Europe/Madrid
      - NETDATA_CLAIM_TOKEN=${NETDATA_CLAIM_TOKEN}
      - NETDATA_CLAIM_ROOMS=${NETDATA_CLAIM_ROOMS}
      - NETDATA_CLAIM_URL=${NETDATA_CLAIM_URL}
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "1"
    restart: unless-stopped

volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
